[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
multiboot2 = { version = "0.18.1", default-features = false }
spin = "0.9.8"
volatile = "0.5.1"
