name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy, rust-src
        target: x86_64-unknown-none

    - uses: ilammy/setup-nasm@v1
      name: Install nasm


    - uses: actions/checkout@v3

    - name: Build
      run: make all

    - name: Test
      run: make test

